"""Regenerate the docs pages that mirror folder READMEs.

Run from the repository root after editing one of the source READMEs:

    python3 docs/sync-imports.py

The CI docs workflow runs this before every site build, so the published
pages never drift from the READMEs even if the script is forgotten locally.
"""
BANNER = '''<div class="oj-banner" markdown>

![OrientationJ](assets/logo-orientationj.png){ .oj-logo }

<p class="oj-subtitle">A series of ImageJ and Fiji plugins for local directional image analysis</p>

<hr>

<p class="oj-author"><a href="mailto:daniel.sage@epfl.ch">Daniel Sage</a> · <a href="https://imaging.epfl.ch/">Center for Imaging</a> and <a href="https://bigwww.epfl.ch/">Biomedical Imaging Group</a>, <a href="https://www.epfl.ch/">Ecole Polytechnique Fédérale de Lausanne (EPFL)</a></p>

<p class="oj-date">August 2026</p>

<hr>

![Color survey of the Tree Rings sample, sweeping the local window](assets/tree-orientation.gif){ .oj-tree }

</div>
'''

EXTERNAL_DATASETS = '''
## External datasets with ground truth

For validation beyond a smoke test, published datasets are also useful:

- **Hotaling et al. (2015), *Data in Brief*** — synthetic fiber images drawn at specified angles, SEM images of steel wire with known diameters, electrospun nanofiber SEM images, their segmentations, and reference orientation histograms. [doi:10.1016/j.dib.2015.07.012](https://doi.org/10.1016/j.dib.2015.07.012)
- **Arafat et al. (2025), *PLOS ONE*** — four extracellular-matrix datasets with manually delineated ground truth, used to benchmark seven fiber-tracing algorithms. [doi:10.1371/journal.pone.0320006](https://doi.org/10.1371/journal.pone.0320006)
'''

PAGES = {
    'docs/test-images.md': ('orientationj-test-images/README.md', EXTERNAL_DATASETS),
    'docs/benchmarking.md': ('assessment/benchmarking_tools/README.md', ''),
}

for page, (source, extra) in PAGES.items():
    content = open(source, encoding='utf-8').read().strip()
    header = (f'<!-- AUTO-GENERATED from {source} by docs/sync-imports.py.\n'
              f'     Do not edit this file: edit the source README, then run\n'
              f'     `python3 docs/sync-imports.py` from the repository root. -->\n\n')
    open(page, 'w', encoding='utf-8').write(
        header + BANNER + '\n' + content + '\n' + extra)
    print(f'{page}  <-  {source}')
