"""Regenerate the docs pages that mirror a README elsewhere in the repository.

Run from the repository root after editing one of the source READMEs:

    python3 docs/sync-imports.py

The CI docs workflow runs this before every site build, so the published
pages never drift from the READMEs even if the script is forgotten locally.
"""
# docs page  <-  source README  (+ extra material appended to the page only)
# "Other tools" is not appended here: the benchmarking README carries it itself.
PAGES = {
    'docs/test-images.md': ('orientationj-test-images/README.md', ''),
    'docs/assessment-benchmarking.md': ('assessment/benchmarking/README.md', ''),
    'docs/assessment-gradients.md': ('assessment/gradients/README.md', ''),
    'docs/assessment-operator.md': ('assessment/gst_operator/README.md', ''),
    'docs/assessment-python-port.md': ('assessment/orientationj_python_port/README.md', ''),
}

for page, (source, extra) in PAGES.items():
    content = open(source, encoding='utf-8').read().strip()
    header = (f'<!-- AUTO-GENERATED from {source} by docs/sync-imports.py.\n'
              f'     Do not edit this file: edit the source README, then run\n'
              f'     `python3 docs/sync-imports.py` from the repository root. -->\n\n')
    open(page, 'w', encoding='utf-8').write(
        header + content + '\n' + extra)
    print(f'{page}  <-  {source}')
